config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root'static_page#home'
  get '/help',   to:'static_page#help', as:'helf'
  get '/about',  to:'static_page#about'
  get '/contact',to:'static_page#contact'
  get '/signup',to:'users#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html:'hello,world!'
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end

  def help
  end


  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title='')
        base_title = "Ruby on Rails Tutorial Sample App"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end        
    end
    
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About" ,about_path %></li>
      <li><%= link_to"Contact",contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-flaxed-top navbar-inverse">
<div class="container">
<%=link_to "sample app",root_path,id:"logo"%>
<nav>
<ul class="nav navbar-nav navbar-right">
<li><%= link_to "Home",root_path%></li>
<li><%= link_to "Help",helf_path %></li>
<li><%= link_to "Log in", "#" %></li>
</ul>
</nav>
</div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if it IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%# 改行定义了所有的页面都将使用provied方法定义标题 %>
    <title> <%= full_title(yield(:title))%></title>
    <%= render 'layouts/rails_default' %>
    <%= render'layouts/shim' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render'layouts/footer' %>
  </div>
  </body>
</html>

app/views/static_page/about.html.erb
<% provide(:title ,"About")%>
<h1>About</h1>
<p>
  the <a href="http://railstutorial.org"><em>Ruby on Rails Tutorial</em></a>is a <a href="http://screencasts.railsTutorial/org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org">Ruby on Rails</a>
  this is the sample application for the tutorial
</p>

app/views/static_page/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutoial.org/contact">contact page</a>
</p>

app/views/static_page/help.html.erb
<% provide(:title,"Help")%>
<h1>HELP</h1>
<p>Get help the Ruby on Rails Tutorial at the<a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em></a></p>

app/views/static_page/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>
  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby onRails Tutorial</a>
  </h2>
  <%= link_to "Sign up now",signup_path,class:"btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag('railsLogo.jpeg',alt: "rails"),'http://rubyonrails.org/'  %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users</p>